export interface IItem {
    code: string
    name: string
    scie: string
    lang: string
    grup: string
    regn: number
    tags: string
    enerc: number
    enerc_e: number
    water: number
    water_e: number
    ash: number
    ash_e: number
    vit: number
    vit_e: number
    fatce: number
    fatce_e: number
    cholc: number
    cholc_e: number
    fibtg: number
    fibtg_e: number
    choavldf: number
    choavldf_e: number
    protcnt: number
    protcnt_e: number
    amiac: number
    amiac_e: number
    cartoid: number
    cartoid_e: number
    polyph: number
    polyph_e: number
    phystr: number
    phystr_e: number
    tocph: number
    tocph_e: number
    toctr: number
    toctr_e: number
    orgac: number
    orgac_e: number
    phytac: number
    phytac_e: number
    sapon: number
    sapon_e: number
    mnrleq: number
    mnrleq_e: number
    mnrlet: number
    mnrlet_e: number
    mnrlpet: number
    mnrlpet_e: number
    mnrlnet: number
    mnrlnet_e: number
    mnrltx: number
    mnrltx_e: number
    vita: number
    vita_e: number
    vitb: number
    vitb_e: number
    vitc: number
    vitc_e: number
    vitd: number
    vitd_e: number
    vite: number
    vite_e: number
    vitk: number
    vitk_e: number
    fasat: number
    fasat_e: number
    fauns: number
    fauns_e: number
    faess: number
    faess_e: number
    facis: number
    facis_e: number
    fatrn: number
    fatrn_e: number
    fams: number
    fams_e: number
    fapu: number
    fapu_e: number
    facn3: number
    facn3_e: number
    facn6: number
    facn6_e: number
    facn9: number
    facn9_e: number
    facn5: number
    facn5_e: number
    facn7: number
    facn7_e: number
    fibins: number
    fibins_e: number
    fibsol: number
    fibsol_e: number
    cho: number
    cho_e: number
    starch: number
    starch_e: number
    olsac: number
    olsac_e: number
    fsugar: number
    fsugar_e: number
    amiace: number
    amiace_e: number
    amiacce: number
    amiacce_e: number
    amiacne: number
    amiacne_e: number
    retol: number
    retol_e: number
    thia: number
    thia_e: number
    ribf: number
    ribf_e: number
    nia: number
    nia_e: number
    pantac: number
    pantac_e: number
    vitb6c: number
    vitb6c_e: number
    biot: number
    biot_e: number
    folsum: number
    folsum_e: number
    ergcal: number
    ergcal_e: number
    chocal: number
    chocal_e: number
    doh25: number
    doh25_e: number
    tocpha: number
    tocpha_e: number
    tocphb: number
    tocphb_e: number
    tocphg: number
    tocphg_e: number
    tocphd: number
    tocphd_e: number
    toctra: number
    toctra_e: number
    toctrb: number
    toctrb_e: number
    toctrg: number
    toctrg_e: number
    toctrd: number
    toctrd_e: number
    vitk1: number
    vitk1_e: number
    vitk2: number
    vitk2_e: number
    lutn: number
    lutn_e: number
    zea: number
    zea_e: number
    lycpn: number
    lycpn_e: number
    crypxb: number
    crypxb_e: number
    cartg: number
    cartg_e: number
    carta: number
    carta_e: number
    cartb: number
    cartb_e: number
    al: number
    al_e: number
    as: number
    as_e: number
    cd: number
    cd_e: number
    ca: number
    ca_e: number
    cr: number
    cr_e: number
    co: number
    co_e: number
    cu: number
    cu_e: number
    fe: number
    fe_e: number
    pb: number
    pb_e: number
    li: number
    li_e: number
    mg: number
    mg_e: number
    mn: number
    mn_e: number
    hg: number
    hg_e: number
    mo: number
    mo_e: number
    ni: number
    ni_e: number
    p: number
    p_e: number
    k: number
    k_e: number
    se: number
    se_e: number
    na: number
    na_e: number
    zn: number
    zn_e: number
    frus: number
    frus_e: number
    glus: number
    glus_e: number
    sucs: number
    sucs_e: number
    mals: number
    mals_e: number
    lactose: number
    lactose_e: number
    f4d0: number
    f4d0_e: number
    f6d0: number
    f6d0_e: number
    f8d0: number
    f8d0_e: number
    f10d0: number
    f10d0_e: number
    f12d0: number
    f12d0_e: number
    f14d0: number
    f14d0_e: number
    f16d0: number
    f16d0_e: number
    f18d0: number
    f18d0_e: number
    f20d0: number
    f20d0_e: number
    f22d0: number
    f22d0_e: number
    f24d0: number
    f24d0_e: number
    f14d1cn5: number
    f14d1cn5_e: number
    f16d1cn7: number
    f16d1cn7_e: number
    f18d1cn9: number
    f18d1cn9_e: number
    f18d1tn9: number
    f18d1tn9_e: number
    f20d1cn9: number
    f20d1cn9_e: number
    f22d1cn9: number
    f22d1cn9_e: number
    f24d1cn9: number
    f24d1cn9_e: number
    f18d2cn6: number
    f18d2cn6_e: number
    f20d2n6: number
    f20d2n6_e: number
    f18d3n3: number
    f18d3n3_e: number
    f20d4n6: number
    f20d4n6_e: number
    f11d0: number
    f11d0_e: number
    f15d0: number
    f15d0_e: number
    f20d3n6: number
    f20d3n6_e: number
    f20d5n3: number
    f20d5n3_e: number
    f22d6n3: number
    f22d6n3_e: number
    f22d2n6: number
    f22d2n6_e: number
    f22d5n3: number
    f22d5n3_e: number
    his: number
    his_e: number
    ile: number
    ile_e: number
    leu: number
    leu_e: number
    lys: number
    lys_e: number
    met: number
    met_e: number
    cys: number
    cys_e: number
    phe: number
    phe_e: number
    thr: number
    thr_e: number
    trp: number
    trp_e: number
    val: number
    val_e: number
    ala: number
    ala_e: number
    arg: number
    arg_e: number
    asp: number
    asp_e: number
    glu: number
    glu_e: number
    gly: number
    gly_e: number
    pro: number
    pro_e: number
    ser: number
    ser_e: number
    tyr: number
    tyr_e: number
    oxalt: number
    oxalt_e: number
    oxals: number
    oxals_e: number
    oxali: number
    oxali_e: number
    caconac: number
    caconac_e: number
    citac: number
    citac_e: number
    fumac: number
    fumac_e: number
    malac: number
    malac_e: number
    quinac: number
    quinac_e: number
    sucac: number
    sucac_e: number
    tarac: number
    tarac_e: number
    dhbenzac34: number
    dhbenzac34_e: number
    hbenzal3: number
    hbenzal3_e: number
    pcathac: number
    pcathac_e: number
    vanlac: number
    vanlac_e: number
    gallac: number
    gallac_e: number
    cinmac: number
    cinmac_e: number
    coumaco: number
    coumaco_e: number
    coumacp: number
    coumacp_e: number
    caffac: number
    caffac_e: number
    chlrac: number
    chlrac_e: number
    ferac: number
    ferac_e: number
    apigen: number
    apigen_e: number
    apigen6cgls: number
    apigen6cgls_e: number
    apigen7onshps: number
    apigen7onshps_e: number
    luteol: number
    luteol_e: number
    kaemf: number
    kaemf_e: number
    querce: number
    querce_e: number
    querce3bdgls: number
    querce3bdgls_e: number
    querce3ortns: number
    querce3ortns_e: number
    querce3bgls: number
    querce3bgls_e: number
    isormt: number
    isormt_e: number
    myrct: number
    myrct_e: number
    rsvrtol: number
    rsvrtol_e: number
    hespt: number
    hespt_e: number
    narng: number
    narng_e: number
    hespd: number
    hespd_e: number
    daidzn: number
    daidzn_e: number
    gnstein: number
    gnstein_e: number
    epicatec: number
    epicatec_e: number
    epicategc: number
    epicategc_e: number
    epicatgc3gal: number
    epicatgc3gal_e: number
    catec: number
    catec_e: number
    galcatecgal: number
    galcatecgal_e: number
    galcatec: number
    galcatec_e: number
    syrgac: number
    syrgac_e: number
    sinpac: number
    sinpac_e: number
    ellgac: number
    ellgac_e: number
    rafs: number
    rafs_e: number
    stas: number
    stas_e: number
    vers: number
    vers_e: number
    ajgs: number
    ajgs_e: number
    camt: number
    camt_e: number
    stgstr: number
    stgstr_e: number
    stostrb: number
    stostrb_e: number
    carot: number
    carot_e: number
    xantp: number
    xantp_e: number
    cartbeq: number
    cartbeq_e: number
  }